#! /bin/sh
ca-parallel exit
ca-parallel add host j-t32c1
ca-parallel add host j-t32c2
ca-parallel add host j-t32c3
#ca-parallel add host j-rdesk
#ca-parallel add host j-xdesk
ca-parallel add search --symmetric=200 --out=ring200.gen S1- S2- S3-
ca-parallel list hosts
ca-parallel list processes
ca-parallel list ranges
